export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE"
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE"
export const FETCH_CURRENT_USER_EXPERIENCES = "FETCH_CURRENT_USER_EXPERIENCES"
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS"
export const FETCH_INSPECTED_USER = "FETCH_INSPECTED_USER"